###  라이브러리 numpy concatenate(...)

* 행렬에 행(row) 또는 열(column)을 추가하기 위한 numpy.concatenate(...)
    - 머신러닝의 회귀(regression)코드 구현시 가중치(weight)와 바이어스(bias)를 별도로 구분하지 않고 하나의 행렬로 취급하기 위한 프로그래밍 구현 기술

In [1]:
#행렬에 열과 행 추가
import numpy as np

A = np.array([[10,20,30], [40,50,60]])

print(A.shape)

#A matrix에 행(row) 추가할 행렬. 1행 3열로 reshape
# 행을 추가하기 때문에 우선 열을 3열로 만들어야 함
row_add = np.array([70, 80, 90]).reshape(1,3) # vector 가 아니라 행렬 특성을 갖도록 reshape 해준 것이다.

#A matrix에 열(column)을 추가할 행렬. 2행 1열로 생성
# 열을 추가하기 때문에 우선 행을 2행으로 만들어야 함
column_add = np.array([1000, 2000]).reshape(2,1)
print(column_add.shape)

#numpy.concatenate 에서 axis = 0 행(row) 기준 
# A 행렬에 row_add 행렬 추가
B = np.concatenate((A, row_add), axis = 0)

print(B)
# numpy.concatenate 에서 axis = 1열(column) 기준
# B 행렬에 column_add 행렬 추가
C = np.concatenate((A, column_add), axis = 1)

print(C)

(2, 3)
(2, 1)
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[  10   20   30 1000]
 [  40   50   60 2000]]
