### 미분 derivative

* 미분
    - 순간 변화율
    - 한 점에서 접점의 기울기

* 미분을 왜 하는가? 미분으로 얻을 수 있는 인사이트?


![image](https://user-images.githubusercontent.com/63198352/89120559-4ac7be80-d4f2-11ea-9ddb-b53e4b758689.png)




![image](https://user-images.githubusercontent.com/63198352/89120762-c5450e00-d4f3-11ea-94b4-583352192f4a.png)

* 미분이 0 이라는 의미는 입력 x가 미세하게 변할 때 함수 변화는 0, 즉 함수는 어떤 변화도 없다는 것을 의미


 ![image](https://user-images.githubusercontent.com/63198352/89120896-cf1b4100-d4f4-11ea-8697-cbf4d63b38e6.png)

* 편미분은 입력변수가 하나 이상인 다변수 함수에서, 미분하고자 하는 변수 하나를 제외한 나머지 변수들은 상수로 취급하고, 해당 변수를 미분하는 것.

### 연쇄법칙 - chain rule
* 합성함수란 여러 함수로 구성된 함수로서, 이러한 합성함수를 미분하려면 '합성함수를 구성하는 각 함수의 미분의 곱'으로 나타내는 chain rule(연쇄법칙) 이용

* 편미분과 chain rule은 머신러닝에서 가중치를 업데이트 하고 오차역전파에서 중요하게 쓰인다
![image](https://user-images.githubusercontent.com/63198352/89121680-d2fe9180-d4fb-11ea-89af-30bd50918c64.png)


### 파이썬 수치 미분 코드 

 ![image](https://user-images.githubusercontent.com/63198352/89121920-2a9dfc80-d4fe-11ea-84fb-e00005ea6287.png)

![image](https://user-images.githubusercontent.com/63198352/89121977-89fc0c80-d4fe-11ea-9e1b-9acff93bf20a.png)

 ![image](https://user-images.githubusercontent.com/63198352/89122389-aa799600-d501-11ea-8feb-301848bf0d02.png)

![image](https://user-images.githubusercontent.com/63198352/89122426-f88e9980-d501-11ea-95ee-a99460b7eb0e.png)

 ![image](https://user-images.githubusercontent.com/63198352/89122519-a7cb7080-d502-11ea-9f97-c2c901bde0f5.png)
 

In [3]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

### ![image](https://user-images.githubusercontent.com/63198352/89123050-612c4500-d507-11ea-846a-cf038317c559.png)


In [8]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =", x)  
    # 함수의 모든 입력변수 값을 출력하고 있다.
    print("debug 2. initial grad =", grad)
    # 모든 입력변수의 미분값을 저장하는 변수 grad를 0으로 초기화한 것을 보여줌
    print("========================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])
        # iterator가 가리키는 입력변수 값을 보여줌
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx])
        # 현재 입력변수에 계산된 미분값을 출력
        print("debug 5. grad =", grad)
        # 계산된 모든 미분값을 가지고 있는 grad 변수의 내용을 출력
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

def func1(input_obj):
    
    x = input_obj[0]
    
    return x**2

numerical_derivative(func1, np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. grad[idx] =  6.000000000012662
debug 5. grad = [6.]


array([6.])

### 2변수 함수  

![image](https://user-images.githubusercontent.com/63198352/89123222-b9177b80-d508-11ea-809f-686251f27975.png)

In [7]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =", x)  
    # 함수의 모든 입력변수 값을 출력하고 있다.
    print("debug 2. initial grad =", grad)
    # 모든 입력변수의 미분값을 저장하는 변수 grad를 0으로 초기화한 것을 보여줌
    print("========================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])
        # iterator가 가리키는 입력변수 값을 보여줌
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx])
        # 현재 입력변수에 계산된 미분값을 출력
        print("debug 5. grad =", grad)
        # 계산된 모든 미분값을 가지고 있는 grad 변수의 내용을 출력
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

def func1(input_obj):
    
    x = input_obj[0] # 첫번째 원소값
    y = input_obj[1] # 두번째 원소 값
    
    return ( 2*x + 3*x*y + np.power(y,3))

#(x, y) = (1.0, 2.0) 에서의 편미분 값
input = np.array([1.0, 2.0])
numerical_derivative(func1, input)

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  7.999999999990237
debug 5. grad = [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000010019221
debug 5. grad = [ 8.         15.00000001]


array([ 8.        , 15.00000001])

###  4변수 함수

### ![image](https://user-images.githubusercontent.com/63198352/89123251-f24feb80-d508-11ea-86a4-b4bccac8af00.png)


In [10]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =", x)  
    # 함수의 모든 입력변수 값을 출력하고 있다.
    print("debug 2. initial grad =", grad)
    # 모든 입력변수의 미분값을 저장하는 변수 grad를 0으로 초기화한 것을 보여줌
    print("========================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])
        # iterator가 가리키는 입력변수 값을 보여줌
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print("debug 4. grad[idx] = ", grad[idx])
        # 현재 입력변수에 계산된 미분값을 출력
        print("debug 5. grad =", grad)
        # 계산된 모든 미분값을 가지고 있는 grad 변수의 내용을 출력
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()
    
    return grad

# 입력변수 4개인 함수
# f(w,x,y,z) = wx + xyz + 3w + zy^2
# input_obj 는 행렬

def func1(input_obj):
    
    w = input_obj[0, 0] 
    x = input_obj[0 ,1]
    y = input_obj[1 ,0]
    z = input_obj[1 ,1]
    
    return ( w*x + x*y*z + 3*w + z*np.power(y,2))

# 입력을 2X2 행렬로 구성함
input = np.array([[1.0, 2.0], [3.0, 4.0]])
numerical_derivative(func1, input)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  5.000000000023874
debug 5. grad = [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  13.00000000000523
debug 5. grad = [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  32.00000000006753
debug 5. grad = [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  15.000000000000568
debug 5. grad = [[ 5. 13.]
 [32. 15.]]


array([[ 5., 13.],
       [32., 15.]])